###
GET http://localhost:9000/v1/restaurants HTTP/1.1

###
GET http://localhost:9000/v1/restaurant/1 HTTP/1.1

###
POST http://localhost:9000/v1/restaurants HTTP/1.1
content-type: application/json

{
    "name": "MacDonald",
    "type": "fastfood",
    "rating": 3
}

###

PATCH http://localhost:9000/v1/restaurant/3 HTTP/1.1
content-type: application/json

{
    "name": "KFC",
    "type": "Soul food!"
}

###
DELETE  http://localhost:9000/v1/restaurant/2 HTTP/1.1



###
POST  http://localhost:9000/v1/user/register HTTP/1.1
content-type: application/json

{
    "name": "MAC",
    "email": "mac@gmail.com",
    "password": "123"
}

###
GET http://localhost:9000/v1/users HTTP/1.1

###
POST http://localhost:9000/v1/user/login HTTP/1.1
content-type: application/json

{
    "email": "abc@gmail.com",
    "password": "123"
}

###
GET http://localhost:9000/v1/user/logout HTTP/1.1

###
GET http://localhost:9000/auth/test HTTP/1.1